# This is a basic workflow to help you get started with Actions

name: check-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install balena-cli
      run: |
        sudo apt-get update 
        sudo apt-get install -y curl git python g++ make
        sudo npm install balena-cli -g --production --unsafe-perm
    - name: Run balena cli raspberry pi (1, Zero, Zero W)
      run: balena build --deviceType raspberry-pi --arch armv6hf --emulated .
    - name: Run balena cli raspberry pi 2
      run: balena build --deviceType raspberry-pi2 --arch armv7hf --emulated .
    - name: Run balena cli raspberry pi 3
      run: balena build --deviceType raspberrypi3 --arch armv7hf --emulated .
    - name: Run balena cli raspberry pi 3 64
      run: balena build --deviceType raspberrypi3-64 --arch aarch64 --emulated .
    - name: Run balena cli raspberry pi 4
      run: balena build --deviceType raspberrypi4-64 --arch aarch64 --emulated .
